### PR TITLE
(bugfix) Fix ResultSetMetaData.isSigned

### LINKED ISSUE #280: ClickHouseResultSetMetaData.isSigned is wrong
I believe  [`ClickHouseResultSetMetaData.isSigned`](https://github.com/housepower/ClickHouse-Native-JDBC/blob/99f221532501b1dfe30d91fb21b6ca4e65c949eb/clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java#L99) is wrong

```JAVA
    public boolean isSigned(int index) throws SQLException {
        return header.getColumnByPosition(index - 1).name().startsWith("U");
    }
```
we should fix it as 

```java
    public boolean isSigned(int index) throws SQLException {
        return !header.getColumnByPosition(index - 1).type().name().startsWith("U");
    }
```

### PR DESCRIPTION
**Pull request by sundy-li**
closes #280

### CODE REVIEW

**Comment by pan3793** [comment]
Benchmark Report
===
```
Benchmark                                           (batchSize)  (columnNum)  (selectNumber)  Mode  Cnt      Score   Error  Units
InsertIBenchmark.benchInsertHttp                         200000           20             N/A  avgt         357.635          ms/op
InsertIBenchmark.benchInsertHttp                         200000           50             N/A  avgt         351.578          ms/op
InsertIBenchmark.benchInsertHttp                         500000           20             N/A  avgt         933.892          ms/op
InsertIBenchmark.benchInsertHttp                         500000           50             N/A  avgt         941.658          ms/op
InsertIBenchmark.benchInsertNative                       200000           20             N/A  avgt          78.590          ms/op
InsertIBenchmark.benchInsertNative                       200000           50             N/A  avgt          73.785          ms/op
InsertIBenchmark.benchInsertNative                       500000           20             N/A  avgt         173.155          ms/op
InsertIBenchmark.benchInsertNative                       500000           50             N/A  avgt         187.897          ms/op
RowBinaryDoubleIBenchmark.benchInsertHttpRowBinary       200000           20             N/A  avgt         218.392          ms/op
RowBinaryDoubleIBenchmark.benchInsertHttpRowBinary       200000           50             N/A  avgt         563.028          ms/op
RowBinaryDoubleIBenchmark.benchInsertHttpRowBinary       500000           20             N/A  avgt         506.348          ms/op
RowBinaryDoubleIBenchmark.benchInsertHttpRowBinary       500000           50             N/A  avgt        1150.134          ms/op
RowBinaryDoubleIBenchmark.benchInsertNative              200000           20             N/A  avgt         348.428          ms/op
RowBinaryDoubleIBenchmark.benchInsertNative              200000           50             N/A  avgt         971.587          ms/op
RowBinaryDoubleIBenchmark.benchInsertNative              500000           20             N/A  avgt         848.879          ms/op
RowBinaryDoubleIBenchmark.benchInsertNative              500000           50             N/A  avgt        2313.596          ms/op
RowBinaryIntIBenchmark.benchInsertHttpRowBinary          200000           20             N/A  avgt         164.507          ms/op
RowBinaryIntIBenchmark.benchInsertHttpRowBinary          200000           50             N/A  avgt         421.777          ms/op
RowBinaryIntIBenchmark.benchInsertHttpRowBinary          500000           20             N/A  avgt         400.433          ms/op
RowBinaryIntIBenchmark.benchInsertHttpRowBinary          500000           50             N/A  avgt        1063.987          ms/op
RowBinaryIntIBenchmark.benchInsertNative                 200000           20             N/A  avgt         217.340          ms/op
RowBinaryIntIBenchmark.benchInsertNative                 200000           50             N/A  avgt         512.801          ms/op
RowBinaryIntIBenchmark.benchInsertNative                 500000           20             N/A  avgt         586.999          ms/op
RowBinaryIntIBenchmark.benchInsertNative                 500000           50             N/A  avgt        1463.938          ms/op
RowBinaryStringIBenchmark.benchInsertHttpRowBinary       200000           20             N/A  avgt         435.652          ms/op
RowBinaryStringIBenchmark.benchInsertHttpRowBinary       200000           50             N/A  avgt        1096.885          ms/op
RowBinaryStringIBenchmark.benchInsertHttpRowBinary       500000           20             N/A  avgt        1046.338          ms/op
RowBinaryStringIBenchmark.benchInsertHttpRowBinary       500000           50             N/A  avgt        2741.049          ms/op
RowBinaryStringIBenchmark.benchInsertNative              200000           20             N/A  avgt         512.728          ms/op
RowBinaryStringIBenchmark.benchInsertNative              200000           50             N/A  avgt        1306.090          ms/op
RowBinaryStringIBenchmark.benchInsertNative              500000           20             N/A  avgt        1156.000          ms/op
RowBinaryStringIBenchmark.benchInsertNative              500000           50             N/A  avgt        3152.432          ms/op
SelectIBenchmark.benchSelectHTTP                            N/A          N/A          500000  avgt        1115.137          ms/op
SelectIBenchmark.benchSelectHTTP                            N/A          N/A        10000000  avgt       22919.338          ms/op
SelectIBenchmark.benchSelectNative                          N/A          N/A          500000  avgt         240.145          ms/op
SelectIBenchmark.benchSelectNative                          N/A          N/A        10000000  avgt        4563.145          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertHttp         200000           20             N/A  avgt         780.069          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertHttp         200000           50             N/A  avgt        2057.564          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertHttp         500000           20             N/A  avgt        1978.327          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertHttp         500000           50             N/A  avgt        5083.540          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertNative       200000           20             N/A  avgt         365.179          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertNative       200000           50             N/A  avgt         991.944          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertNative       500000           20             N/A  avgt         861.367          ms/op
WideColumnDoubleInsertIBenchmark.benchInsertNative       500000           50             N/A  avgt        2373.477          ms/op
WideColumnIntInsertIBenchmark.benchInsertHttp            200000           20             N/A  avgt         395.656          ms/op
WideColumnIntInsertIBenchmark.benchInsertHttp            200000           50             N/A  avgt        1024.127          ms/op
WideColumnIntInsertIBenchmark.benchInsertHttp            500000           20             N/A  avgt        1045.734          ms/op
WideColumnIntInsertIBenchmark.benchInsertHttp            500000           50             N/A  avgt        2566.761          ms/op
WideColumnIntInsertIBenchmark.benchInsertNative          200000           20             N/A  avgt         224.239          ms/op
WideColumnIntInsertIBenchmark.benchInsertNative          200000           50             N/A  avgt         556.704          ms/op
WideColumnIntInsertIBenchmark.benchInsertNative          500000           20             N/A  avgt         556.540          ms/op
WideColumnIntInsertIBenchmark.benchInsertNative          500000           50             N/A  avgt        1434.042          ms/op
WideColumnStringInsertIBenchmark.benchInsertHttp         200000           20             N/A  avgt         484.761          ms/op
WideColumnStringInsertIBenchmark.benchInsertHttp         200000           50             N/A  avgt        1219.833          ms/op
WideColumnStringInsertIBenchmark.benchInsertHttp         500000           20             N/A  avgt        1254.299          ms/op
WideColumnStringInsertIBenchmark.benchInsertHttp         500000           50             N/A  avgt        2985.242          ms/op
WideColumnStringInsertIBenchmark.benchInsertNative       200000           20             N/A  avgt         491.797          ms/op
WideColumnStringInsertIBenchmark.benchInsertNative       200000           50             N/A  avgt        1298.799          ms/op
WideColumnStringInsertIBenchmark.benchInsertNative       500000           20             N/A  avgt        1234.475          ms/op
WideColumnStringInsertIBenchmark.benchInsertNative       500000           50             N/A  avgt        3149.508          ms/op
```

File: clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java [hunk 1]
```diff
@@ -97,7 +97,7 @@ public int isNullable(int index) throws SQLException {
 
     @Override
     public boolean isSigned(int index) throws SQLException {
-        return header.getColumnByPosition(index - 1).name().startsWith("U");
+        return header.getColumnByPosition(index - 1).type().name().startsWith("U");
```
Comment (baibaichen) [inline clickhouse-native-jdbc/src/main/java/com/github/housepower/jdbc/ClickHouseResultSetMetaData.java:100]: U means unsigned？
